=begin
	
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. => e
	
=end

first_number = 1
second_number = 2
puts first_number, second_number

next_number = first_number+second_number
puts next_number
sum = second_number

while next_number < 400000
	puts next_number

	if next_number % 2 == 0
		sum += next_number
	end
	#if the number is even, then add it to the variable sum. 

	first_number = second_number
	second_number = next_number
	next_number = first_number+second_number
end
#Finding the terms in the Fibonacci sequenece up to 4,000,000.

puts
puts sum